### ISSUE TITLE
Cannot upload image from clipboard

### ISSUE THREAD

**Issue by Corona09** [askfiy/nvim-picgo#2]
When uploading image from clipboard, it fails.

![](https://raw.githubusercontent.com/Corona09/images/main/%E6%88%AA%E5%9B%BE%202022-09-03%2010-52-17.png)

**Comment by askfiy** [comment]
Check whether your pico configuration is normal, and it

**Comment by Corona09** [comment]
> Check whether your pico configuration is normal, and it

Picgo's config works well. And nvim-picgo can upload image from file system. but it cannot upload image from clipboard.

**Comment by askfiy** [comment]
Did you successfully send the picture to the system clipboard?

**Comment by Corona09** [comment]
> Did you successfully send the picture to the system clipboard?

sure. when using typora or vscode, images can be uploaded normally from clipboard.

**Comment by askfiy** [comment]
You can enter the command `picgo u` on the command line.

Check whether it can be uploaded successfully.

**Comment by Corona09** [comment]
> You can enter the command `picgo u` on the command line.
> 
> Check whether it can be uploaded successfully.

no, it failed, the output is as below:
```
[PicGo ERROR]: Error: EACCES: permission denied, open '/usr/local/share/.config/yarn/global/node_modules/picgo/dist/linux.sh'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at /usr/local/share/.config/yarn/global/node_modules/picgo/dist/index.cjs.js:1:36231
    at new Promise (<anonymous>)
    at st (/usr/local/share/.config/yarn/global/node_modules/picgo/dist/index.cjs.js:1:35953)
    at dt.upload (/usr/local/share/.config/yarn/global/node_modules/picgo/dist/index.cjs.js:1:44959)
    at /usr/local/share/.config/yarn/global/node_modules/picgo/dist/index.cjs.js:1:3214
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/picgo/dist/index.cjs.js:1:3225)
    at Command.listener [as _actionHandler] (/usr/local/share/.config/yarn/global/node_modules/commander/lib/command.js:488:17)
    at /usr/local/share/.config/yarn/global/node_modules/commander/lib/command.js:1227:65 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/local/share/.config/yarn/global/node_modules/picgo/dist/linux.sh'
}
```

**Comment by askfiy** [comment]
It looks like it should be an upstream issue.

The essence of this plugin is to call the `picgo u` command to upload an image.

Try contacting `picgo-core` for a solution.
