### ISSUE TITLE
active this plug will slow down nvim startup time

### ISSUE THREAD

**Issue by OliverChao** [askfiy/nvim-picgo#3]
This plug is useful, and it makes uploading pics very easy. But, it slows down my nvim undesirably. 
I don't know how this happens, but when I active this plug , my nvim turns to start up slowly.

https://user-images.githubusercontent.com/39361033/204797987-0872b4f7-891f-4cc6-96fe-965be90d3775.mp4

**Comment by askfiy** [comment]
Try adding lazy load:

```lua
{ "askfiy/nvim-picgo", module = "nvim-picgo" },
```

Then call Lua's api command:

```lua
api.map.bulk_register({
    {
        mode = { "n" },
        lhs = "<leader>uc",
        rhs = function()
            require("nvim-picgo").upload_clipboard()
        end,
        options = { silent = true },
        description = "Upload image from clipboard",
    },
    {
        mode = { "n" },
        lhs = "<leader>uf",
        rhs = function()
            require("nvim-picgo").upload_imagefile()
        end,
        options = { silent = true },
        description = "Upload image from disk file",
    },
})
```

Of course this is my approach, you may need to use `vim.keymap.set` or `vim.api.nvim_set_keymap` method.

**Comment by OliverChao** [comment]
THE lazy loading approach is great. 
However, I use vim-plug as my package manager, and I have few experience on lua. 

Now, I want to load nvim-picgo lazily.  
I comment the  "require("nvim-picgo").setup() ". and add your code snippet. 
But nvim complains:
![Screenshot from 2022-12-01 18-44-45](https://user-images.githubusercontent.com/39361033/205033749-5f0a2d50-e39d-45c8-8b81-f5d4fadf3c02.png)

**Comment by askfiy** [comment]
I use packer as plugin manager, so maybe we are not the same..

You can try this:

```vim
Plug 'askfiy/nvim-picgo', { 'on': ['UploadImagefile', 'UploadClipboard'] }
```

Now the plugin will only be loaded when you type `UploadClipboard` or the `UploadClipboard` command.

Of course, you still need to explicitly call the `setup()` function to before use.

I recommend using `packer` over `vim-plug`。

**Comment by OliverChao** [comment]
Thank you very much. Yep, `packer` and `lua` are awesome, and highly configurable. But I also love vim-plug which is straightforward and easy to use.  Anyway, there also exists a way to handle this problem in vim-plug. 

Identify the file type in vim-plug:
```vim
Plug 'askfiy/nvim-picgo', {'for': ['markdown','md']}
```

then, add one auto command in init.vim:
```vim
autocmd FileType markdown lua require("nvim-picgo").setup()
```
And then, this plug will only start up for markdown files.

I have another question: why this plug encumber my `init.vim` and `init.lua` startup? I found nvim-picgo start up very fast but it slow down the two files.

**Comment by askfiy** [comment]
I don't think this is a good idea, `autocmd` will run every time you open an `md` file, which may lead to repeated calls to the `setup` function.

In addition, the code of the `nvim-picgo` plugin is very small, and it may call an external `shell` command to verify that you have installed `picgo-core` when executing `setup`.

What exactly is causing you to be slowed down, I have no idea.

**Comment by OliverChao** [comment]
Yep, that is the problem.  Thanks very much! 
When I forbid the verification process, anything becomes normal. 
Maybe, `nvim-picgo` can use `vim.fn.executable()` instead to check the `picgo`, which is more efficient. 
And, I created a PR here.

Anyway, `vim.fn.executable()` works fine in my `vim-plug` configurations and THANKS again.
